### ISSUE TITLE
use unichars instead of ! x and etc

### ISSUE THREAD

**Issue by tbhaxor** [s0md3v/hue#27]
Like  `ora` (npm package) use unichar and threading supported text for success, fail, info etc prints

**Comment by s0md3v** [comment]
Just one question, why?

**Comment by tbhaxor** [comment]
Because they convey the best message
like `✔` for success and `✖` for error 

anyways its your wish, after all its a suggestion

**Comment by s0md3v** [comment]
"Best" is subjective.
I believe `+` represents something positive & `-` represents something negative that's why I kept it that way but its perfectly normal that you don't think the same.
Everyone has their own personal preferences but that doesn't mean your "best" is better than someone else's "best".
This is open source anyway, so just fork the repo and do whatever you want :)
