### ISSUE TITLE
three dots

### ISSUE THREAD

**Issue by jaromrax** [s0md3v/hue#6]
It is very simple, which is a strength. I would suggest only to add `...` to info,que etc to have more like logger output
```
[+]... text
```

**Comment by s0md3v** [comment]
Thanks for the suggestion @jaromrax but its just a matter of personal preference and hence I can't agree on it because I like it this way.
I am keeping this issue open so other people can vote about which one looks good.
Here's a sample output of current scheme:

<img src="https://xsstrike.tk/images/1.png">

**Comment by aggmoulik** [comment]
I think HUE should have **---- ( strike )** as everyone has its own preference.

**Comment by s0md3v** [comment]
I guess I should close this issue now.
Thanks again.
